#!/bin/sh

# scripts/server: Launch the application and any extra required processes locally.

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
sh scripts/update

# @TODO: ensure we're in local environment.

# start virtualenv.
source .venv/bin/activate

# start app
python run.py

# deactivate virtualenv.
deactivate