#!/bin/sh

# scripts/setup: Set up application for the first time after cloning, or set it back to the initial first unused state.

cd "$(dirname "$0")/.."

sh scripts/bootstrap

# @TODO: Reset database to fresh state.

echo "==> app is now ready to go!"