#!/bin/sh

# scripts/update: Update application to run for its current state.

cd "$(dirname "$0")/.."

sh scripts/bootstrap

# @TODO: run all database migrations to ensure everything is up to date.

echo "==> app is updated!"